status = error
name = SparkLogConfig

# 默认 root 级别
rootLogger.level = warn
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = Console

appender.stdout.type = Console
appender.stdout.name = Console
appender.stdout.layout.type = PatternLayout
appender.stdout.layout.pattern = %d{HH:mm:ss} %-5p %c{1}: %m%n

# Spark / Hadoop / Iceberg 各自的日志级别配置

logger.hadoopnative.name=org.apache.hadoop.util.NativeCodeLoader
logger.hadoopnative.level=error

# logger.spark.name = org.apache.spark
# logger.spark.level = warn
#
# logger.hadoop.name = org.apache.hadoop
# logger.hadoop.level = warn
#
# logger.iceberg.name = org.apache.iceberg
# logger.iceberg.level = warn
